# Generated by Django 6.0.4 on 2026-04-12 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria de Material',
                'verbose_name_plural': 'Categorias de Material',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CompraMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição do Material')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('unidade', models.CharField(choices=[('un', 'Unidade'), ('kg', 'Quilograma'), ('m', 'Metro'), ('m2', 'Metro²'), ('m3', 'Metro³'), ('l', 'Litro'), ('saco', 'Saco'), ('pc', 'Peça'), ('cx', 'Caixa'), ('rl', 'Rolo'), ('vb', 'Verba')], default='un', max_length=10, verbose_name='Unidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('fornecedor', models.CharField(blank=True, max_length=200, verbose_name='Fornecedor')),
                ('nota_fiscal', models.CharField(blank=True, max_length=50, verbose_name='Nota Fiscal')),
                ('data_compra', models.DateField(verbose_name='Data da Compra')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiais.categoriamaterial', verbose_name='Categoria')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='obras.obra', verbose_name='Obra')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Compra de Material',
                'verbose_name_plural': 'Compras de Material',
                'ordering': ['-data_compra', '-criado_em'],
            },
        ),
    ]
