# Generated by Django 6.0.4 on 2026-04-12 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Obra')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('cliente', models.CharField(max_length=200, verbose_name='Cliente')),
                ('endereco', models.CharField(max_length=300, verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('tipo_obra', models.CharField(choices=[('construcao', 'Construção'), ('reforma', 'Reforma'), ('ampliacao', 'Ampliação'), ('manutencao', 'Manutenção'), ('demolicao', 'Demolição')], max_length=20, verbose_name='Tipo de Obra')),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('pausada', 'Pausada'), ('cancelada', 'Cancelada')], default='planejada', max_length=20, verbose_name='Status')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_previsao_fim', models.DateField(verbose_name='Previsão de Término')),
                ('data_fim_real', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('orcamento_previsto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Orçamento Previsto')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obras', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['-criado_em'],
            },
        ),
    ]
